CREATE SEQUENCE IF NOT EXISTS seq_employee_id START WITH 1 INCREMENT BY 1 OWNED BY employees.id;

CREATE SEQUENCE IF NOT EXISTS seq_customer_id START WITH 1 INCREMENT BY 1 OWNED BY customers.id;

CREATE SEQUENCE IF NOT EXISTS seq_address_id START WITH 1 INCREMENT BY 1 OWNED BY addresses.id;

CREATE SEQUENCE IF NOT EXISTS seq_order_id START WITH 1 INCREMENT BY 1 OWNED BY orders.id;

CREATE SEQUENCE IF NOT EXISTS seq_product_audit_id START WITH 1 INCREMENT BY 1 OWNED BY products_audit.id;